#!/bin/bash
set -e

HOST=x86_64-w64-mingw32
MINGW=mingw64
DIST=/dist
EXE_TARGET="${EXE_TARGET:-/target}"

get_libevent() (
    wget https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
    tar -xf libevent-2.1.12-stable.tar.gz
)

get_openssl() (
    wget https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1l.tar.gz
    tar -xf OpenSSL_1_1_1l.tar.gz
)

get_zlib() (
    wget https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz
    tar -xf v1.2.11.tar.gz
)

get_tor() (
    wget https://github.com/torproject/tor/archive/refs/tags/tor-0.4.6.8.tar.gz
    tar -xf tor-0.4.6.8.tar.gz
)

build_libevent() (
    pushd libevent-2.1.12-stable
    ./configure --prefix="$DIST" --host="$HOST" --disable-openssl
    make
    make install
    popd
)

build_openssl() (
    pushd openssl-OpenSSL_1_1_1l
    ./Configure "$MINGW" shared --cross-compile-prefix="$HOST"- --prefix="$DIST"
    make depend
    make -j4
    make install_sw
    popd
)

build_zlib() (
    pushd zlib-1.2.11
    CC="$HOST"-gcc ./configure --prefix="$DIST"
    make
    make install
    popd
)

build_tor() (
    pushd tor-tor-0.4.6.8
    ./autogen.sh
    CFLAGS=-mwindows ./configure \
        --host="$HOST" \
        --enable-static-tor \
        --disable-unittests \
        --disable-system-torrc \
        --disable-manpage \
        --disable-html-manual \
        --disable-asciidoc \
        --disable-gcc-hardening \
        --disable-linker-hardening \
        --disable-tool-name-check \
        --disable-module-dirauth \
        --disable-module-relay \
        --with-libevent-dir="$DIST" \
        --with-openssl-dir="$DIST" \
        --with-zlib-dir="$DIST" \
        --enable-rust \
        --enable-cargo-online-mode
    make -j4

    # copy executable to host
    cp src/app/tor.exe "$EXE_TARGET"
    popd
)

build_tor_static_lib() (
    pushd tor-tor-0.4.6.8/src
    gcc -o mytor.o mytor.c \
        -Llib -Lcore \
        -ltor-app -ltor-compress -ltor-evloop -ltor-tls -ltor-crypt-ops \
        -lcurve25519_donna -ltor-geoip -ltor-process -ltor-time -ltor-fs \
        -ltor-encoding -ltor-sandbox -ltor-container -ltor-net -ltor-thread \
        -ltor-memarea -ltor-math -ltor-meminfo -ltor-osinfo -ltor-log -ltor-lock \
        -ltor-fdio -ltor-string -ltor-term -ltor-smartlist-core -ltor-malloc \
        -ltor-wallclock -ltor-err -ltor-intmath -ltor-ctime -ltor-trace -Lext/keccak-tiny \
        -lkeccak-tiny -Lext/ed25519/ref10 -led25519_ref10 -Lext/ed25519/donna -led25519_donna \
        -Ltrunnel -lor-trunnel -ltor-buf -ltor-version -ltor-pubsub -ltor-dispatch -ltor-container \
        -ltor-confmgt -lm -ltor-metrics -ltor-llharden \
        -L/dist/lib -levent -lz -lssl -lcrypto
    popd
)

## Static libraries
# core/libtor-app.a
# lib/libtor-compress.a
# lib/libtor-evloop.a
# lib/libtor-tls.a
# lib/libtor-crypt-ops.a
# lib/libcurve25519_donna.a
# lib/libtor-geoip.a
# lib/libtor-process.a
# lib/libtor-time.a
# lib/libtor-fs.a
# lib/libtor-encoding.a
# lib/libtor-sandbox.a
# lib/libtor-container.a
# lib/libtor-net.a
# lib/libtor-thread.a
# lib/libtor-memarea.a
# lib/libtor-math.a
# lib/libtor-meminfo.a
# lib/libtor-osinfo.a
# lib/libtor-log.a
# lib/libtor-lock.a
# lib/libtor-fdio.a
# lib/libtor-string.a
# lib/libtor-term.a
# lib/libtor-smartlist-core.a
# lib/libtor-malloc.a
# lib/libtor-wallclock.a
# lib/libtor-err.a
# lib/libtor-intmath.a
# lib/libtor-ctime.a
# lib/libtor-trace.a
# lib/libtor-metrics.a
# lib/libtor-llharden.a
# ext/keccak-tiny/libkeccak-tiny.a
# ext/ed25519/ref10/libed25519_ref10.a
# ext/ed25519/donna/libed25519_donna.a
# trunnel/libor-trunnel.a
# lib/libtor-buf.a
# lib/libtor-version.a
# lib/libtor-pubsub.a
# lib/libtor-dispatch.a
# lib/libtor-container.a
# lib/libtor-confmgt.a
# /usr/lib/x86_64-linux-gnu/libpthread.a
# /usr/lib/x86_64-linux-gnu/libm.a
# /dist/lib/libevent.a
# /dist/lib/libz.a
# /dist/lib/libssl.a
# /dist/lib/libcrypto.a

# directory where compiled executables/libraries/headers will be placed
if [ ! -d "$DIST" ]; then
    mkdir "$DIST"
fi

# Download stuff
get_libevent
get_openssl
get_zlib
get_tor

# Build dependencies
build_libevent
build_zlib
build_openssl

# Finally
build_tor
